### PR TITLE
Bugfix: Fix rate-overlimit issue when there are more than 5 whatsapp channels in a single account

### LINKED ISSUE #1844: WhatsApp bridge: Rate-Overlimit
I don't know if the problem is caused by Matterbridge or WhatsApp. 

Apparently there is a WhatsApp gateway entry limit of 5. If more than 5 gateways are added, the WhatsApp bridge does not start due to the following error:

`Starting gateway failed: bridge whatsapp.mywhatsapp failed to join channel: info query returned status 429: rate-overlimit`

## Steps to reproduce the behavior:
1. Add more than 5 WhatsApp gateways
2. Matterbridge ends abruptly.

## A clear and concise description of what you expected to happen.

Last lines from the output when running: `matterbridge -debug`:

```
[0020]  WARN whatsapp:     [Connect:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/whatsappmulti/whatsapp.go:139] Could not get profile photo of XXXXXX@s.whatsapp.net: failed to get avatar: the user has hidden their profile picture from you
[0021]  INFO whatsapp:     [Connect:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/whatsappmulti/whatsapp.go:149] Finished getting avatars..
[0021]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0022]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0022]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0022]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0023]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0023]  INFO whatsapp:     [joinChannels:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/bridge/bridge.go:77] whatsapp.mywhatsapp: joining XXXX@g.us (ID: XXXX@g.uswhatsapp.mywhatsapp)
[0023] FATAL main:         [main:C:/Users/xx/go/pkg/mod/github.com/42wim/matterbridge@v1.25.2-0.20220604130913-3819062574ac/matterbridge.go:66] Starting gateway failed: Bridge whatsapp.mywhatsapp failed to join channel: info query returned status 429: rate-overlimit
```

**Environment (please complete the following information):**
 - Windows 11, Ubuntu 20.04
 - Version: 1.25.2-dev
 - `go install -tags whatsappmulti github.com/42wim/matterbridge@master`

**Additional context**
Please add your configuration file  (be sure to exclude or anonymize private data (tokens/passwords))

```
[[gateway]]
    name="gateway1"
    enable=true

    [[gateway.in]]  # First gateway
    account="whatsapp.mywhatsapp"
    channel="XXXX@g.us"

    [[anothergateway.in]]
    XXXXX
    XXXXX

[[gateway]]
    name="gateway2"
    enable=true

    [[anothergateway.in]]
    XXXXX
    XXXXX

    [[gateway.out]]  # Second gateway
    account="whatsapp.mywhatsapp"
    channel="XXXX@g.us"

    [[gateway.out]]  # Thirdgateway
    account="whatsapp.mywhatsapp"
    channel="XXXX@g.us"

... and so on

```

ADITIONAL NOTES: 
It was working fine until today when I deleted the 'device' (whatsmeow) from the list of LINKED DEVICES on WhatsApp. Added it again and the error started to appear.

### PR DESCRIPTION
**Pull request by yousefmansy1**
Fix rate-overlimit issue when there are more than 5 whatsapp channels in a single account.
resolves #1844

### CODE REVIEW

File: bridge/whatsappmulti/whatsapp.go [hunk 1]
```diff
@@ -166,19 +172,14 @@ func (b *Bwhatsapp) Disconnect() error {
 func (b *Bwhatsapp) JoinChannel(channel config.ChannelInfo) error {
 	byJid := isGroupJid(channel.Name)
 
-	groups, err := b.wc.GetJoinedGroups()
```
Comment (yousefmansy1) [inline bridge/whatsappmulti/whatsapp.go:169]: In reality 5 was not a hard limit on joined chats or anything.
Rather we were calling `GetJoinedGroups` too frequently and 5 happened to be the rate limit.
We really only care about this a single time per bridge so storing this in the bridge on create should not pose any compatibility issues I believe. 

This will improve bot boot times as get joined groups would add a delay to each channel joined.
And removed the need for multiple devices to work with many WhatsApp chats.

**Comment by 42wim** [comment]
Thanks!
