### PR TITLE
fix double unlock

### LINKED ISSUE #770: panic
running on commit fa4eec41f762dc42bf881befa9058aa636a89eef

```
[2019-03-21T13:22:54Z]  INFO slack:        Large slack detected > 2000 users, skipping loading complete userlist.    
fatal error: sync: Unlock of unlocked RWMutex                                                                        
                                                                                                                     
goroutine 102 [running]:                                                                                             
runtime.throw(0x10d13ca, 0x20)                                                                                       
        /home/matterbridge/go/src/runtime/panic.go:608 +0x72 fp=0xc000547c78 sp=0xc000547c48 pc=0x42dd62             sync.throw(0x10d13ca, 0x20)                               
        /home/matterbridge/go/src/runtime/panic.go:594 +0x35 fp=0xc000547c98 sp=0xc000547c78 pc=0x42dce5             
sync.(*RWMutex).Unlock(0xc000957db8)                                                                                         /home/matterbridge/go/src/sync/rwmutex.go:124 +0xa1 fp=0xc000547cc8 sp=0xc000547c98 pc=0x4747f1              
github.com/42wim/matterbridge/bridge/slack.(*users).populateUser(0xc000957da0, 0xc000e996f0, 0x9)                    
        /home/matterbridge/.go/src/github.com/42wim/matterbridge/bridge/slack/users_channels.go:97 +0x1a7 fp=0xc00054
7d68 sp=0xc000547cc8 pc=0xc3b487                                                                                     
github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlackClient(0xc0004636c0, 0xc0007f3e00)                   
        /home/matterbridge/.go/src/github.com/42wim/matterbridge/bridge/slack/handlers.go:88 +0x472 fp=0xc000547fd0 s
p=0xc000547d68 pc=0xc30ce2                                                                                           
runtime.goexit()                                                                                                     
        /home/matterbridge/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000547fd8 sp=0xc000547fd0 pc=0x45da21          
created by github.com/42wim/matterbridge/bridge/slack.(*Bslack).handleSlack                                          
        /home/matterbridge/.go/src/github.com/42wim/matterbridge/bridge/slack/handlers.go:20 +0x592                  
                                                                                                                     
goroutine 1 [select (no cases), 34 minutes]:                                                                         
main.main()                                                                                                          
        /home/matterbridge/.go/src/github.com/42wim/matterbridge/matterbridge.go:61 +0x5ff                           
                                                                                                                     
goroutine 4 [syscall, 34 minutes]:                                                                                   
os/signal.signal_recv(0x0)                                                                                           
        /home/matterbridge/go/src/runtime/sigqueue.go:139 +0x9c                                                      
os/signal.loop()                                                                                                     
        /home/matterbridge/go/src/os/signal/signal_unix.go:23 +0x22                                                  
created by os/signal.init.0                                                                                          
        /home/matterbridge/go/src/os/signal/signal_unix.go:29 +0x41  
```

### PR DESCRIPTION
**Pull request by dajohi**
Fixes #770

### CODE REVIEW

File: bridge/slack/users_channels.go [hunk 1]
```diff
@@ -87,7 +87,6 @@ func (b *users) populateUser(userID string) {
 			// in case the previous query failed for some reason.
 		} else {
 			b.usersSyncPoints[userID] = make(chan struct{})
-			b.usersMutex.Unlock()
```
Comment (Helcaraxan) [inline bridge/slack/users_channels.go]: This should actually be kept but the `break` on the line below should be a `return` instead.

**Comment by 42wim** [comment]
Thanks!
